import type { Character, Category } from './types';

export interface CategoryRoster {
  id: Category;
  label: string;
  characters: Character[];
}

const youtubers: CategoryRoster = {
  id: 'youtubers',
  label: 'YouTubers',
  characters: [
    { id: 'yt-01', name: 'MrBeast', imageUrl: '/images/categories/youtubers/mrbeast.jpg', gender: 'male' },
    { id: 'yt-02', name: 'PewDiePie', imageUrl: '/images/categories/youtubers/pewdiepie.jpg', gender: 'male' },
    { id: 'yt-03', name: 'Markiplier', imageUrl: '/images/categories/youtubers/markiplier.jpg', gender: 'male' },
    { id: 'yt-04', name: 'KSI', imageUrl: '/images/categories/youtubers/ksi.jpg', gender: 'male' },
    { id: 'yt-05', name: 'Logan Paul', imageUrl: '/images/categories/youtubers/logan-paul.jpg', gender: 'male' },
    { id: 'yt-06', name: 'Jake Paul', imageUrl: '/images/categories/youtubers/jake-paul.jpg', gender: 'male' },
    { id: 'yt-07', name: 'Jacksepticeye', imageUrl: '/images/categories/youtubers/jacksepticeye.jpg', gender: 'male' },
    { id: 'yt-08', name: 'Dream', imageUrl: '/images/categories/youtubers/dream.jpg', gender: 'male' },
    { id: 'yt-09', name: 'Ninja', imageUrl: '/images/categories/youtubers/ninja.jpg', gender: 'male' },
    { id: 'yt-10', name: 'IShowSpeed', imageUrl: '/images/categories/youtubers/ishowspeed.jpg', gender: 'male' },
    { id: 'yt-11', name: 'Jenna Marbles', imageUrl: '/images/categories/youtubers/jenna-marbles.jpg', gender: 'female' },
    { id: 'yt-12', name: 'Liza Koshy', imageUrl: '/images/categories/youtubers/liza-koshy.jpg', gender: 'female' },
    { id: 'yt-13', name: 'Emma Chamberlain', imageUrl: '/images/categories/youtubers/emma-chamberlain.jpg', gender: 'female' },
    { id: 'yt-14', name: 'David Dobrik', imageUrl: '/images/categories/youtubers/david-dobrik.jpg', gender: 'male' },
    { id: 'yt-15', name: 'Dude Perfect', imageUrl: '/images/categories/youtubers/dude-perfect.jpg', gender: 'male' },
    { id: 'yt-16', name: 'SSSniperWolf', imageUrl: '/images/categories/youtubers/sssniperwolf.jpg', gender: 'female' },
    { id: 'yt-17', name: 'Pokimane', imageUrl: '/images/categories/youtubers/pokimane.jpg', gender: 'female' },
    { id: 'yt-18', name: 'Valkyrae', imageUrl: '/images/categories/youtubers/valkyrae.jpg', gender: 'female' },
    { id: 'yt-19', name: 'CoryxKenshin', imageUrl: '/images/categories/youtubers/coryxkenshin.jpg', gender: 'male' },
    { id: 'yt-20', name: 'Kai Cenat', imageUrl: '/images/categories/youtubers/kai-cenat.jpg', gender: 'male' },
    { id: 'yt-21', name: 'MatPat', imageUrl: '/images/categories/youtubers/matpat.jpg', gender: 'male' },
    { id: 'yt-22', name: 'Rhett McLaughlin', imageUrl: '/images/categories/youtubers/rhett-mclaughlin.jpg', gender: 'male' },
    { id: 'yt-23', name: 'Link Neal', imageUrl: '/images/categories/youtubers/link-neal.jpg', gender: 'male' },
    { id: 'yt-24', name: 'Lilly Singh', imageUrl: '/images/categories/youtubers/lilly-singh.jpg', gender: 'female' },
    { id: 'yt-25', name: 'Rosanna Pansino', imageUrl: '/images/categories/youtubers/rosanna-pansino.jpg', gender: 'female' },
    { id: 'yt-26', name: 'Casey Neistat', imageUrl: '/images/categories/youtubers/casey-neistat.jpg', gender: 'male' },
    { id: 'yt-27', name: 'Preston', imageUrl: '/images/categories/youtubers/preston.jpg', gender: 'male' },
    { id: 'yt-28', name: 'Typical Gamer', imageUrl: '/images/categories/youtubers/typical-gamer.jpg', gender: 'male' },
  ],
};

const musicArtists: CategoryRoster = {
  id: 'music_artists',
  label: 'Music Artists',
  characters: [
    { id: 'mu-01', name: 'Taylor Swift', imageUrl: '/images/categories/music-artists/taylor-swift.jpg', gender: 'female' },
    { id: 'mu-02', name: 'Drake', imageUrl: '/images/categories/music-artists/drake.jpg', gender: 'male' },
    { id: 'mu-03', name: 'Beyoncé', imageUrl: '/images/categories/music-artists/beyonce.jpg', gender: 'female' },
    { id: 'mu-04', name: 'Ed Sheeran', imageUrl: '/images/categories/music-artists/ed-sheeran.jpg', gender: 'male' },
    { id: 'mu-05', name: 'Rihanna', imageUrl: '/images/categories/music-artists/rihanna.jpg', gender: 'female' },
    { id: 'mu-06', name: 'Kanye West', imageUrl: '/images/categories/music-artists/kanye-west.jpg', gender: 'male' },
    { id: 'mu-07', name: 'Adele', imageUrl: '/images/categories/music-artists/adele.jpg', gender: 'female' },
    { id: 'mu-08', name: 'Bruno Mars', imageUrl: '/images/categories/music-artists/bruno-mars.jpg', gender: 'male' },
    { id: 'mu-09', name: 'Billie Eilish', imageUrl: '/images/categories/music-artists/billie-eilish.jpg', gender: 'female' },
    { id: 'mu-10', name: 'The Weeknd', imageUrl: '/images/categories/music-artists/the-weeknd.jpg', gender: 'male' },
    { id: 'mu-11', name: 'Ariana Grande', imageUrl: '/images/categories/music-artists/ariana-grande.jpg', gender: 'female' },
    { id: 'mu-12', name: 'Post Malone', imageUrl: '/images/categories/music-artists/post-malone.jpg', gender: 'male' },
    { id: 'mu-13', name: 'Dua Lipa', imageUrl: '/images/categories/music-artists/dua-lipa.jpg', gender: 'female' },
    { id: 'mu-14', name: 'Travis Scott', imageUrl: '/images/categories/music-artists/travis-scott.jpg', gender: 'male' },
    { id: 'mu-15', name: 'Doja Cat', imageUrl: '/images/categories/music-artists/doja-cat.jpg', gender: 'female' },
    { id: 'mu-16', name: 'Harry Styles', imageUrl: '/images/categories/music-artists/harry-styles.jpg', gender: 'male' },
    { id: 'mu-17', name: 'SZA', imageUrl: '/images/categories/music-artists/sza.jpg', gender: 'female' },
    { id: 'mu-18', name: 'Bad Bunny', imageUrl: '/images/categories/music-artists/bad-bunny.jpg', gender: 'male' },
    { id: 'mu-19', name: 'Olivia Rodrigo', imageUrl: '/images/categories/music-artists/olivia-rodrigo.jpg', gender: 'female' },
    { id: 'mu-20', name: 'Kendrick Lamar', imageUrl: '/images/categories/music-artists/kendrick-lamar.jpg', gender: 'male' },
    { id: 'mu-21', name: 'Lady Gaga', imageUrl: '/images/categories/music-artists/lady-gaga.jpg', gender: 'female' },
    { id: 'mu-22', name: 'Justin Bieber', imageUrl: '/images/categories/music-artists/justin-bieber.jpg', gender: 'male' },
    { id: 'mu-23', name: 'Nicki Minaj', imageUrl: '/images/categories/music-artists/nicki-minaj.jpg', gender: 'female' },
    { id: 'mu-24', name: 'Lil Nas X', imageUrl: '/images/categories/music-artists/lil-nas-x.jpg', gender: 'male' },
    { id: 'mu-25', name: 'Megan Thee Stallion', imageUrl: '/images/categories/music-artists/megan-thee-stallion.jpg', gender: 'female' },
    { id: 'mu-26', name: 'Sam Smith', imageUrl: '/images/categories/music-artists/sam-smith.jpg', gender: 'male' },
    { id: 'mu-27', name: 'Cardi B', imageUrl: '/images/categories/music-artists/cardi-b.jpg', gender: 'female' },
    { id: 'mu-28', name: 'Eminem', imageUrl: '/images/categories/music-artists/eminem.jpg', gender: 'male' },
  ],
};

const actors: CategoryRoster = {
  id: 'actors',
  label: 'Movie/TV Actors',
  characters: [
    { id: 'ac-01', name: 'Dwayne Johnson', imageUrl: '/images/categories/actors/dwayne-johnson.jpg', gender: 'male' },
    { id: 'ac-02', name: 'Zendaya', imageUrl: '/images/categories/actors/zendaya.jpg', gender: 'female' },
    { id: 'ac-03', name: 'Tom Holland', imageUrl: '/images/categories/actors/tom-holland.jpg', gender: 'male' },
    { id: 'ac-04', name: 'Margot Robbie', imageUrl: '/images/categories/actors/margot-robbie.jpg', gender: 'female' },
    { id: 'ac-05', name: 'Ryan Reynolds', imageUrl: '/images/categories/actors/ryan-reynolds.jpg', gender: 'male' },
    { id: 'ac-06', name: 'Scarlett Johansson', imageUrl: '/images/categories/actors/scarlett-johansson.jpg', gender: 'female' },
    { id: 'ac-07', name: 'Leonardo DiCaprio', imageUrl: '/images/categories/actors/leonardo-dicaprio.jpg', gender: 'male' },
    { id: 'ac-08', name: 'Jennifer Lawrence', imageUrl: '/images/categories/actors/jennifer-lawrence.jpg', gender: 'female' },
    { id: 'ac-09', name: 'Chris Hemsworth', imageUrl: '/images/categories/actors/chris-hemsworth.jpg', gender: 'male' },
    { id: 'ac-10', name: 'Florence Pugh', imageUrl: '/images/categories/actors/florence-pugh.jpg', gender: 'female' },
    { id: 'ac-11', name: 'Robert Downey Jr.', imageUrl: '/images/categories/actors/robert-downey-jr.jpg', gender: 'male' },
    { id: 'ac-12', name: 'Ana de Armas', imageUrl: '/images/categories/actors/ana-de-armas.jpg', gender: 'female' },
    { id: 'ac-13', name: 'Timothée Chalamet', imageUrl: '/images/categories/actors/timothee-chalamet.jpg', gender: 'male' },
    { id: 'ac-14', name: 'Sydney Sweeney', imageUrl: '/images/categories/actors/sydney-sweeney.jpg', gender: 'female' },
    { id: 'ac-15', name: 'Keanu Reeves', imageUrl: '/images/categories/actors/keanu-reeves.jpg', gender: 'male' },
    { id: 'ac-16', name: 'Emma Stone', imageUrl: '/images/categories/actors/emma-stone.jpg', gender: 'female' },
    { id: 'ac-17', name: 'Will Smith', imageUrl: '/images/categories/actors/will-smith.jpg', gender: 'male' },
    { id: 'ac-18', name: 'Millie Bobby Brown', imageUrl: '/images/categories/actors/millie-bobby-brown.jpg', gender: 'female' },
    { id: 'ac-19', name: 'Pedro Pascal', imageUrl: '/images/categories/actors/pedro-pascal.jpg', gender: 'male' },
    { id: 'ac-20', name: 'Anya Taylor-Joy', imageUrl: '/images/categories/actors/anya-taylor-joy.jpg', gender: 'female' },
    { id: 'ac-21', name: 'Morgan Freeman', imageUrl: '/images/categories/actors/morgan-freeman.jpg', gender: 'male' },
    { id: 'ac-22', name: 'Viola Davis', imageUrl: '/images/categories/actors/viola-davis.jpg', gender: 'female' },
    { id: 'ac-23', name: 'Chris Pratt', imageUrl: '/images/categories/actors/chris-pratt.jpg', gender: 'male' },
    { id: 'ac-24', name: 'Jenna Ortega', imageUrl: '/images/categories/actors/jenna-ortega.jpg', gender: 'female' },
    { id: 'ac-25', name: 'Cillian Murphy', imageUrl: '/images/categories/actors/cillian-murphy.jpg', gender: 'male' },
    { id: 'ac-26', name: 'Sandra Bullock', imageUrl: '/images/categories/actors/sandra-bullock.jpg', gender: 'female' },
    { id: 'ac-27', name: 'Jason Momoa', imageUrl: '/images/categories/actors/jason-momoa.jpg', gender: 'male' },
    { id: 'ac-28', name: 'Lupita Nyong\'o', imageUrl: '/images/categories/actors/lupita-nyongo.jpg', gender: 'female' },
  ],
};

const athletes: CategoryRoster = {
  id: 'athletes',
  label: 'Athletes',
  characters: [
    { id: 'at-01', name: 'LeBron James', imageUrl: '/images/categories/athletes/lebron-james.jpg', gender: 'male' },
    { id: 'at-02', name: 'Serena Williams', imageUrl: '/images/categories/athletes/serena-williams.jpg', gender: 'female' },
    { id: 'at-03', name: 'Lionel Messi', imageUrl: '/images/categories/athletes/lionel-messi.jpg', gender: 'male' },
    { id: 'at-04', name: 'Simone Biles', imageUrl: '/images/categories/athletes/simone-biles.jpg', gender: 'female' },
    { id: 'at-05', name: 'Cristiano Ronaldo', imageUrl: '/images/categories/athletes/cristiano-ronaldo.jpg', gender: 'male' },
    { id: 'at-06', name: 'Naomi Osaka', imageUrl: '/images/categories/athletes/naomi-osaka.jpg', gender: 'female' },
    { id: 'at-07', name: 'Stephen Curry', imageUrl: '/images/categories/athletes/stephen-curry.jpg', gender: 'male' },
    { id: 'at-08', name: 'Sha\'Carri Richardson', imageUrl: '/images/categories/athletes/shacarri-richardson.jpg', gender: 'female' },
    { id: 'at-09', name: 'Tom Brady', imageUrl: '/images/categories/athletes/tom-brady.jpg', gender: 'male' },
    { id: 'at-10', name: 'Alex Morgan', imageUrl: '/images/categories/athletes/alex-morgan.jpg', gender: 'female' },
    { id: 'at-11', name: 'Usain Bolt', imageUrl: '/images/categories/athletes/usain-bolt.jpg', gender: 'male' },
    { id: 'at-12', name: 'Megan Rapinoe', imageUrl: '/images/categories/athletes/megan-rapinoe.jpg', gender: 'female' },
    { id: 'at-13', name: 'Patrick Mahomes', imageUrl: '/images/categories/athletes/patrick-mahomes.jpg', gender: 'male' },
    { id: 'at-14', name: 'Katie Ledecky', imageUrl: '/images/categories/athletes/katie-ledecky.jpg', gender: 'female' },
    { id: 'at-15', name: 'Kevin Durant', imageUrl: '/images/categories/athletes/kevin-durant.jpg', gender: 'male' },
    { id: 'at-16', name: 'Coco Gauff', imageUrl: '/images/categories/athletes/coco-gauff.jpg', gender: 'female' },
    { id: 'at-17', name: 'Neymar', imageUrl: '/images/categories/athletes/neymar.jpg', gender: 'male' },
    { id: 'at-18', name: 'Eileen Gu', imageUrl: '/images/categories/athletes/eileen-gu.jpg', gender: 'female' },
    { id: 'at-19', name: 'Giannis Antetokounmpo', imageUrl: '/images/categories/athletes/giannis-antetokounmpo.jpg', gender: 'male' },
    { id: 'at-20', name: 'Sydney McLaughlin', imageUrl: '/images/categories/athletes/sydney-mclaughlin.jpg', gender: 'female' },
    { id: 'at-21', name: 'Kylian Mbappé', imageUrl: '/images/categories/athletes/kylian-mbappe.jpg', gender: 'male' },
    { id: 'at-22', name: 'Ronda Rousey', imageUrl: '/images/categories/athletes/ronda-rousey.jpg', gender: 'female' },
    { id: 'at-23', name: 'Mike Tyson', imageUrl: '/images/categories/athletes/mike-tyson.jpg', gender: 'male' },
    { id: 'at-24', name: 'Caitlin Clark', imageUrl: '/images/categories/athletes/caitlin-clark.jpg', gender: 'female' },
    { id: 'at-25', name: 'Shaquille O\'Neal', imageUrl: '/images/categories/athletes/shaquille-oneal.jpg', gender: 'male' },
    { id: 'at-26', name: 'Venus Williams', imageUrl: '/images/categories/athletes/venus-williams.jpg', gender: 'female' },
    { id: 'at-27', name: 'Tiger Woods', imageUrl: '/images/categories/athletes/tiger-woods.jpg', gender: 'male' },
    { id: 'at-28', name: 'Lindsey Vonn', imageUrl: '/images/categories/athletes/lindsey-vonn.jpg', gender: 'female' },
  ],
};

const bibleCharacters: CategoryRoster = {
  id: 'bible_characters',
  label: 'Bible Characters',
  characters: [
    { id: 'bi-01', name: 'Moses', imageUrl: '/images/categories/bible-characters/moses.jpg', gender: 'male' },
    { id: 'bi-02', name: 'Mary', imageUrl: '/images/categories/bible-characters/mary.jpg', gender: 'female' },
    { id: 'bi-03', name: 'David', imageUrl: '/images/categories/bible-characters/david.jpg', gender: 'male' },
    { id: 'bi-04', name: 'Esther', imageUrl: '/images/categories/bible-characters/esther.jpg', gender: 'female' },
    { id: 'bi-05', name: 'Abraham', imageUrl: '/images/categories/bible-characters/abraham.jpg', gender: 'male' },
    { id: 'bi-06', name: 'Ruth', imageUrl: '/images/categories/bible-characters/ruth.jpg', gender: 'female' },
    { id: 'bi-07', name: 'Noah', imageUrl: '/images/categories/bible-characters/noah.jpg', gender: 'male' },
    { id: 'bi-08', name: 'Deborah', imageUrl: '/images/categories/bible-characters/deborah.jpg', gender: 'female' },
    { id: 'bi-09', name: 'Joseph', imageUrl: '/images/categories/bible-characters/joseph.jpg', gender: 'male' },
    { id: 'bi-10', name: 'Rahab', imageUrl: '/images/categories/bible-characters/rahab.jpg', gender: 'female' },
    { id: 'bi-11', name: 'Daniel', imageUrl: '/images/categories/bible-characters/daniel.jpg', gender: 'male' },
    { id: 'bi-12', name: 'Sarah', imageUrl: '/images/categories/bible-characters/sarah.jpg', gender: 'female' },
    { id: 'bi-13', name: 'Samson', imageUrl: '/images/categories/bible-characters/samson.jpg', gender: 'male' },
    { id: 'bi-14', name: 'Hannah', imageUrl: '/images/categories/bible-characters/hannah.jpg', gender: 'female' },
    { id: 'bi-15', name: 'Elijah', imageUrl: '/images/categories/bible-characters/elijah.jpg', gender: 'male' },
    { id: 'bi-16', name: 'Miriam', imageUrl: '/images/categories/bible-characters/miriam.jpg', gender: 'female' },
    { id: 'bi-17', name: 'Solomon', imageUrl: '/images/categories/bible-characters/solomon.jpg', gender: 'male' },
    { id: 'bi-18', name: 'Rebekah', imageUrl: '/images/categories/bible-characters/rebekah.jpg', gender: 'female' },
    { id: 'bi-19', name: 'Peter', imageUrl: '/images/categories/bible-characters/peter.jpg', gender: 'male' },
    { id: 'bi-20', name: 'Mary Magdalene', imageUrl: '/images/categories/bible-characters/mary-magdalene.jpg', gender: 'female' },
    { id: 'bi-21', name: 'Paul', imageUrl: '/images/categories/bible-characters/paul.jpg', gender: 'male' },
    { id: 'bi-22', name: 'Eve', imageUrl: '/images/categories/bible-characters/eve.jpg', gender: 'female' },
    { id: 'bi-23', name: 'Adam', imageUrl: '/images/categories/bible-characters/adam.jpg', gender: 'male' },
    { id: 'bi-24', name: 'Delilah', imageUrl: '/images/categories/bible-characters/delilah.jpg', gender: 'female' },
    { id: 'bi-25', name: 'Joshua', imageUrl: '/images/categories/bible-characters/joshua.jpg', gender: 'male' },
    { id: 'bi-26', name: 'Jezebel', imageUrl: '/images/categories/bible-characters/jezebel.jpg', gender: 'female' },
    { id: 'bi-27', name: 'Jonah', imageUrl: '/images/categories/bible-characters/jonah.jpg', gender: 'male' },
    { id: 'bi-28', name: 'Bathsheba', imageUrl: '/images/categories/bible-characters/bathsheba.jpg', gender: 'female' },
  ],
};

const famousFaces: CategoryRoster = {
  id: 'famous_faces',
  label: 'Famous Faces',
  characters: [
    { id: 'ff-01', name: 'Elon Musk', imageUrl: '/images/categories/famous-faces/elon-musk.jpg', gender: 'male' },
    { id: 'ff-02', name: 'Oprah Winfrey', imageUrl: '/images/categories/famous-faces/oprah-winfrey.jpg', gender: 'female' },
    { id: 'ff-03', name: 'Barack Obama', imageUrl: '/images/categories/famous-faces/barack-obama.jpg', gender: 'male' },
    { id: 'ff-04', name: 'Michelle Obama', imageUrl: '/images/categories/famous-faces/michelle-obama.jpg', gender: 'female' },
    { id: 'ff-05', name: 'Mark Zuckerberg', imageUrl: '/images/categories/famous-faces/mark-zuckerberg.jpg', gender: 'male' },
    { id: 'ff-06', name: 'Malala Yousafzai', imageUrl: '/images/categories/famous-faces/malala-yousafzai.jpg', gender: 'female' },
    { id: 'ff-07', name: 'Jeff Bezos', imageUrl: '/images/categories/famous-faces/jeff-bezos.jpg', gender: 'male' },
    { id: 'ff-08', name: 'Kim Kardashian', imageUrl: '/images/categories/famous-faces/kim-kardashian.jpg', gender: 'female' },
    { id: 'ff-09', name: 'Bill Gates', imageUrl: '/images/categories/famous-faces/bill-gates.jpg', gender: 'male' },
    { id: 'ff-10', name: 'Taylor Lorenz', imageUrl: '/images/categories/famous-faces/taylor-lorenz.jpg', gender: 'female' },
    { id: 'ff-11', name: 'Donald Trump', imageUrl: '/images/categories/famous-faces/donald-trump.jpg', gender: 'male' },
    { id: 'ff-12', name: 'Greta Thunberg', imageUrl: '/images/categories/famous-faces/greta-thunberg.jpg', gender: 'female' },
    { id: 'ff-13', name: 'Joe Rogan', imageUrl: '/images/categories/famous-faces/joe-rogan.jpg', gender: 'male' },
    { id: 'ff-14', name: 'Alexandria Ocasio-Cortez', imageUrl: '/images/categories/famous-faces/alexandria-ocasio-cortez.jpg', gender: 'female' },
    { id: 'ff-15', name: 'Neil deGrasse Tyson', imageUrl: '/images/categories/famous-faces/neil-degrasse-tyson.jpg', gender: 'male' },
    { id: 'ff-16', name: 'Emma Watson', imageUrl: '/images/categories/famous-faces/emma-watson.jpg', gender: 'female' },
    { id: 'ff-17', name: 'Gordon Ramsay', imageUrl: '/images/categories/famous-faces/gordon-ramsay.jpg', gender: 'male' },
    { id: 'ff-18', name: 'Kylie Jenner', imageUrl: '/images/categories/famous-faces/kylie-jenner.jpg', gender: 'female' },
    { id: 'ff-19', name: 'Snoop Dogg', imageUrl: '/images/categories/famous-faces/snoop-dogg.jpg', gender: 'male' },
    { id: 'ff-20', name: 'Serena Williams', imageUrl: '/images/categories/famous-faces/serena-williams.jpg', gender: 'female' },
    { id: 'ff-21', name: 'Steve Harvey', imageUrl: '/images/categories/famous-faces/steve-harvey.jpg', gender: 'male' },
    { id: 'ff-22', name: 'Ellen DeGeneres', imageUrl: '/images/categories/famous-faces/ellen-degeneres.jpg', gender: 'female' },
    { id: 'ff-23', name: 'Kevin Hart', imageUrl: '/images/categories/famous-faces/kevin-hart.jpg', gender: 'male' },
    { id: 'ff-24', name: 'Martha Stewart', imageUrl: '/images/categories/famous-faces/martha-stewart.jpg', gender: 'female' },
    { id: 'ff-25', name: 'Dwayne Johnson', imageUrl: '/images/categories/famous-faces/dwayne-johnson.jpg', gender: 'male' },
    { id: 'ff-26', name: 'Queen Elizabeth II', imageUrl: '/images/categories/famous-faces/queen-elizabeth-ii.jpg', gender: 'female' },
    { id: 'ff-27', name: 'Pope Francis', imageUrl: '/images/categories/famous-faces/pope-francis.jpg', gender: 'male' },
    { id: 'ff-28', name: 'Ruth Bader Ginsburg', imageUrl: '/images/categories/famous-faces/ruth-bader-ginsburg.jpg', gender: 'female' },
  ],
};

export const categoryRosters: CategoryRoster[] = [
  youtubers,
  musicArtists,
  actors,
  athletes,
  bibleCharacters,
  famousFaces,
];

export function getCategoryRoster(category: Category): CategoryRoster | null {
  return categoryRosters.find(r => r.id === category) ?? null;
}
