import type { Character, Category } from './types';

export interface CategoryRoster {
  id: Category;
  label: string;
  characters: Character[];
}

const digitalCreators: CategoryRoster = {
  id: 'digital_creators',
  label: 'Digital Creators & Reality TV',
  characters: [
    { id: 'dc-01', name: 'KSI', imageUrl: '/images/categories/digital-creators/ksi.jpg', gender: 'male' },
    { id: 'dc-02', name: 'Miniminter', imageUrl: '/images/categories/digital-creators/miniminter.jpg', gender: 'male' },
    { id: 'dc-03', name: 'Vikkstar123', imageUrl: '/images/categories/digital-creators/vikkstar123.jpg', gender: 'male' },
    { id: 'dc-04', name: 'W2S', imageUrl: '/images/categories/digital-creators/w2s.jpg', gender: 'male' },
    { id: 'dc-05', name: 'Niko Omilana', imageUrl: '/images/categories/digital-creators/niko-omilana.jpg', gender: 'male' },
    { id: 'dc-06', name: 'Chunkz', imageUrl: '/images/categories/digital-creators/chunkz.jpg', gender: 'male' },
    { id: 'dc-07', name: 'Yung Filly', imageUrl: '/images/categories/digital-creators/yung-filly.jpg', gender: 'male' },
    { id: 'dc-08', name: 'GK Barry', imageUrl: '/images/categories/digital-creators/gk-barry.jpg', gender: 'female' },
    { id: 'dc-09', name: 'Madame Joyce', imageUrl: '/images/categories/digital-creators/madame-joyce.jpg', gender: 'female' },
    { id: 'dc-10', name: 'Maya Jama', imageUrl: '/images/categories/digital-creators/maya-jama.jpg', gender: 'female' },
    { id: 'dc-11', name: 'Amelia Dimoldenberg', imageUrl: '/images/categories/digital-creators/amelia-dimoldenberg.jpg', gender: 'female' },
    { id: 'dc-12', name: 'Olivia Attwood', imageUrl: '/images/categories/digital-creators/olivia-attwood.jpg', gender: 'female' },
    { id: 'dc-13', name: 'Tommy Fury', imageUrl: '/images/categories/digital-creators/tommy-fury.jpg', gender: 'male' },
    { id: 'dc-14', name: 'Molly-Mae Hague', imageUrl: '/images/categories/digital-creators/molly-mae-hague.jpg', gender: 'female' },
    { id: 'dc-15', name: 'MrBeast', imageUrl: '/images/categories/digital-creators/mrbeast.jpg', gender: 'male' },
    { id: 'dc-16', name: 'Logan Paul', imageUrl: '/images/categories/digital-creators/logan-paul.jpg', gender: 'male' },
    { id: 'dc-17', name: 'Jake Paul', imageUrl: '/images/categories/digital-creators/jake-paul.jpg', gender: 'male' },
    { id: 'dc-18', name: 'Ryan Trahan', imageUrl: '/images/categories/digital-creators/ryan-trahan.jpg', gender: 'male' },
    { id: 'dc-19', name: 'PewDiePie', imageUrl: '/images/categories/digital-creators/pewdiepie.jpg', gender: 'male' },
    { id: 'dc-20', name: 'Emma Chamberlain', imageUrl: '/images/categories/digital-creators/emma-chamberlain.jpg', gender: 'female' },
    { id: 'dc-21', name: 'James Charles', imageUrl: '/images/categories/digital-creators/james-charles.jpg', gender: 'male' },
    { id: 'dc-22', name: 'Jeffree Star', imageUrl: '/images/categories/digital-creators/jeffree-star.jpg', gender: 'male' },
    { id: 'dc-23', name: 'David Dobrik', imageUrl: '/images/categories/digital-creators/david-dobrik.jpg', gender: 'male' },
    { id: 'dc-24', name: 'Addison Rae', imageUrl: '/images/categories/digital-creators/addison-rae.jpg', gender: 'female' },
    { id: 'dc-25', name: 'Charli D\'Amelio', imageUrl: '/images/categories/digital-creators/charli-damelio.jpg', gender: 'female' },
    { id: 'dc-26', name: 'Khaby Lame', imageUrl: '/images/categories/digital-creators/khaby-lame.jpg', gender: 'male' },
    { id: 'dc-27', name: 'Zach King', imageUrl: '/images/categories/digital-creators/zach-king.jpg', gender: 'male' },
    { id: 'dc-28', name: 'JoJo Siwa', imageUrl: '/images/categories/digital-creators/jojo-siwa.jpg', gender: 'female' },
    { id: 'dc-29', name: 'Marques Brownlee', imageUrl: '/images/categories/digital-creators/marques-brownlee.jpg', gender: 'male' },
    { id: 'dc-30', name: 'Mercy Eke', imageUrl: '/images/categories/digital-creators/mercy-eke.jpg', gender: 'female' },
    { id: 'dc-31', name: 'Nengi Hampson', imageUrl: '/images/categories/digital-creators/nengi-hampson.jpg', gender: 'female' },
    { id: 'dc-32', name: 'Laycon', imageUrl: '/images/categories/digital-creators/laycon.jpg', gender: 'male' },
    { id: 'dc-33', name: 'Whitemoney', imageUrl: '/images/categories/digital-creators/whitemoney.jpg', gender: 'male' },
    { id: 'dc-34', name: 'Neo Akpofure', imageUrl: '/images/categories/digital-creators/neo-akpofure.jpg', gender: 'male' },
    { id: 'dc-35', name: 'Uti Nwachukwu', imageUrl: '/images/categories/digital-creators/uti-nwachukwu.jpg', gender: 'male' },
    { id: 'dc-36', name: 'Tacha Akide', imageUrl: '/images/categories/digital-creators/tacha-akide.jpg', gender: 'female' },
    { id: 'dc-37', name: 'Kiddwaya', imageUrl: '/images/categories/digital-creators/kiddwaya.jpg', gender: 'male' },
    { id: 'dc-38', name: 'Cee-C', imageUrl: '/images/categories/digital-creators/cee-c.jpg', gender: 'female' },
    { id: 'dc-39', name: 'Ebuka Obi-Uchendu', imageUrl: '/images/categories/digital-creators/ebuka-obi-uchendu.jpg', gender: 'male' },
    { id: 'dc-40', name: 'Ekin-Su Culculoglu', imageUrl: '/images/categories/digital-creators/ekin-su-culculoglu.jpg', gender: 'female' },
    { id: 'dc-41', name: 'Indiyah Polack', imageUrl: '/images/categories/digital-creators/indiyah-polack.jpg', gender: 'female' },
    { id: 'dc-42', name: 'Dami Hope', imageUrl: '/images/categories/digital-creators/dami-hope.jpg', gender: 'male' },
    { id: 'dc-43', name: 'Sam Thompson', imageUrl: '/images/categories/digital-creators/sam-thompson.jpg', gender: 'male' },
    { id: 'dc-44', name: 'Amber Gill', imageUrl: '/images/categories/digital-creators/amber-gill.jpg', gender: 'female' },
    { id: 'dc-45', name: 'Maura Higgins', imageUrl: '/images/categories/digital-creators/maura-higgins.jpg', gender: 'female' },
    { id: 'dc-46', name: 'Joey Essex', imageUrl: '/images/categories/digital-creators/joey-essex.jpg', gender: 'male' },
    { id: 'dc-47', name: 'Justine Ndiba', imageUrl: '/images/categories/digital-creators/justine-ndiba.jpg', gender: 'female' },
    { id: 'dc-48', name: 'Francesca Farago', imageUrl: '/images/categories/digital-creators/francesca-farago.jpg', gender: 'female' },
    { id: 'dc-49', name: 'Chloe Veitch', imageUrl: '/images/categories/digital-creators/chloe-veitch.jpg', gender: 'female' },
    { id: 'dc-50', name: 'Harry Jowsey', imageUrl: '/images/categories/digital-creators/harry-jowsey.jpg', gender: 'male' },
  ],
};

const musicArtists: CategoryRoster = {
  id: 'music_artists',
  label: 'Music Artists',
  characters: [
    { id: 'mu-01', name: 'Taylor Swift', imageUrl: '/images/categories/music-artists/taylor-swift.jpg', gender: 'female' },
    { id: 'mu-02', name: 'Drake', imageUrl: '/images/categories/music-artists/drake.jpg', gender: 'male' },
    { id: 'mu-03', name: 'Beyoncé', imageUrl: '/images/categories/music-artists/beyonce.jpg', gender: 'female' },
    { id: 'mu-04', name: 'Ed Sheeran', imageUrl: '/images/categories/music-artists/ed-sheeran.jpg', gender: 'male' },
    { id: 'mu-05', name: 'Rihanna', imageUrl: '/images/categories/music-artists/rihanna.jpg', gender: 'female' },
    { id: 'mu-06', name: 'Kanye West', imageUrl: '/images/categories/music-artists/kanye-west.jpg', gender: 'male' },
    { id: 'mu-07', name: 'Adele', imageUrl: '/images/categories/music-artists/adele.jpg', gender: 'female' },
    { id: 'mu-08', name: 'Bruno Mars', imageUrl: '/images/categories/music-artists/bruno-mars.jpg', gender: 'male' },
    { id: 'mu-09', name: 'Billie Eilish', imageUrl: '/images/categories/music-artists/billie-eilish.jpg', gender: 'female' },
    { id: 'mu-10', name: 'The Weeknd', imageUrl: '/images/categories/music-artists/the-weeknd.jpg', gender: 'male' },
    { id: 'mu-11', name: 'Ariana Grande', imageUrl: '/images/categories/music-artists/ariana-grande.jpg', gender: 'female' },
    { id: 'mu-12', name: 'Post Malone', imageUrl: '/images/categories/music-artists/post-malone.jpg', gender: 'male' },
    { id: 'mu-13', name: 'Dua Lipa', imageUrl: '/images/categories/music-artists/dua-lipa.jpg', gender: 'female' },
    { id: 'mu-14', name: 'Travis Scott', imageUrl: '/images/categories/music-artists/travis-scott.jpg', gender: 'male' },
    { id: 'mu-15', name: 'Doja Cat', imageUrl: '/images/categories/music-artists/doja-cat.jpg', gender: 'female' },
    { id: 'mu-16', name: 'Harry Styles', imageUrl: '/images/categories/music-artists/harry-styles.jpg', gender: 'male' },
    { id: 'mu-17', name: 'SZA', imageUrl: '/images/categories/music-artists/sza.jpg', gender: 'female' },
    { id: 'mu-18', name: 'Bad Bunny', imageUrl: '/images/categories/music-artists/bad-bunny.jpg', gender: 'male' },
    { id: 'mu-19', name: 'Olivia Rodrigo', imageUrl: '/images/categories/music-artists/olivia-rodrigo.jpg', gender: 'female' },
    { id: 'mu-20', name: 'Kendrick Lamar', imageUrl: '/images/categories/music-artists/kendrick-lamar.jpg', gender: 'male' },
    { id: 'mu-21', name: 'Lady Gaga', imageUrl: '/images/categories/music-artists/lady-gaga.jpg', gender: 'female' },
    { id: 'mu-22', name: 'Justin Bieber', imageUrl: '/images/categories/music-artists/justin-bieber.jpg', gender: 'male' },
    { id: 'mu-23', name: 'Nicki Minaj', imageUrl: '/images/categories/music-artists/nicki-minaj.jpg', gender: 'female' },
    { id: 'mu-24', name: 'Lil Nas X', imageUrl: '/images/categories/music-artists/lil-nas-x.jpg', gender: 'male' },
    { id: 'mu-25', name: 'Megan Thee Stallion', imageUrl: '/images/categories/music-artists/megan-thee-stallion.jpg', gender: 'female' },
    { id: 'mu-26', name: 'Sam Smith', imageUrl: '/images/categories/music-artists/sam-smith.jpg', gender: 'male' },
    { id: 'mu-27', name: 'Cardi B', imageUrl: '/images/categories/music-artists/cardi-b.jpg', gender: 'female' },
    { id: 'mu-28', name: 'Eminem', imageUrl: '/images/categories/music-artists/eminem.jpg', gender: 'male' },
    { id: 'mu-29', name: 'Chris Brown', imageUrl: '/images/categories/music-artists/chris-brown.jpg', gender: 'male' },
    { id: 'mu-30', name: 'Future', imageUrl: '/images/categories/music-artists/future.jpg', gender: 'male' },
    { id: 'mu-31', name: 'J. Cole', imageUrl: '/images/categories/music-artists/j-cole.jpg', gender: 'male' },
    { id: 'mu-32', name: '21 Savage', imageUrl: '/images/categories/music-artists/21-savage.jpg', gender: 'male' },
    { id: 'mu-33', name: 'Tyler, the Creator', imageUrl: '/images/categories/music-artists/tyler-the-creator.jpg', gender: 'male' },
    { id: 'mu-34', name: 'Ice Spice', imageUrl: '/images/categories/music-artists/ice-spice.jpg', gender: 'female' },
    { id: 'mu-35', name: 'Roddy Ricch', imageUrl: '/images/categories/music-artists/roddy-ricch.jpg', gender: 'male' },
    { id: 'mu-36', name: 'Lil Baby', imageUrl: '/images/categories/music-artists/lil-baby.jpg', gender: 'male' },
    { id: 'mu-37', name: 'Gunna', imageUrl: '/images/categories/music-artists/gunna.jpg', gender: 'male' },
    { id: 'mu-38', name: 'Young Thug', imageUrl: '/images/categories/music-artists/young-thug.jpg', gender: 'male' },
    { id: 'mu-39', name: 'Metro Boomin', imageUrl: '/images/categories/music-artists/metro-boomin.jpg', gender: 'male' },
    { id: 'mu-40', name: 'Playboi Carti', imageUrl: '/images/categories/music-artists/playboi-carti.jpg', gender: 'male' },
    { id: 'mu-41', name: 'Central Cee', imageUrl: '/images/categories/music-artists/central-cee.jpg', gender: 'male' },
    { id: 'mu-42', name: 'Stormzy', imageUrl: '/images/categories/music-artists/stormzy.jpg', gender: 'male' },
    { id: 'mu-43', name: 'Dave', imageUrl: '/images/categories/music-artists/dave.jpg', gender: 'male' },
    { id: 'mu-44', name: 'Burna Boy', imageUrl: '/images/categories/music-artists/burna-boy.jpg', gender: 'male' },
    { id: 'mu-45', name: 'Wizkid', imageUrl: '/images/categories/music-artists/wizkid.jpg', gender: 'male' },
    { id: 'mu-46', name: 'Davido', imageUrl: '/images/categories/music-artists/davido.jpg', gender: 'male' },
    { id: 'mu-47', name: 'Tems', imageUrl: '/images/categories/music-artists/tems.jpg', gender: 'female' },
    { id: 'mu-48', name: 'Rema', imageUrl: '/images/categories/music-artists/rema.jpg', gender: 'male' },
    { id: 'mu-49', name: 'Ayra Starr', imageUrl: '/images/categories/music-artists/ayra-starr.jpg', gender: 'female' },
    { id: 'mu-50', name: 'Asake', imageUrl: '/images/categories/music-artists/asake.jpg', gender: 'male' },
  ],
};

const actors: CategoryRoster = {
  id: 'actors',
  label: 'Movie/TV Actors',
  characters: [
    { id: 'ac-01', name: 'Dwayne Johnson', imageUrl: '/images/categories/actors/dwayne-johnson.jpg', gender: 'male' },
    { id: 'ac-02', name: 'Zendaya', imageUrl: '/images/categories/actors/zendaya.jpg', gender: 'female' },
    { id: 'ac-03', name: 'Tom Holland', imageUrl: '/images/categories/actors/tom-holland.jpg', gender: 'male' },
    { id: 'ac-04', name: 'Margot Robbie', imageUrl: '/images/categories/actors/margot-robbie.jpg', gender: 'female' },
    { id: 'ac-05', name: 'Ryan Reynolds', imageUrl: '/images/categories/actors/ryan-reynolds.jpg', gender: 'male' },
    { id: 'ac-06', name: 'Scarlett Johansson', imageUrl: '/images/categories/actors/scarlett-johansson.jpg', gender: 'female' },
    { id: 'ac-07', name: 'Leonardo DiCaprio', imageUrl: '/images/categories/actors/leonardo-dicaprio.jpg', gender: 'male' },
    { id: 'ac-08', name: 'Jennifer Lawrence', imageUrl: '/images/categories/actors/jennifer-lawrence.jpg', gender: 'female' },
    { id: 'ac-09', name: 'Chris Hemsworth', imageUrl: '/images/categories/actors/chris-hemsworth.jpg', gender: 'male' },
    { id: 'ac-10', name: 'Florence Pugh', imageUrl: '/images/categories/actors/florence-pugh.jpg', gender: 'female' },
    { id: 'ac-11', name: 'Robert Downey Jr.', imageUrl: '/images/categories/actors/robert-downey-jr.jpg', gender: 'male' },
    { id: 'ac-12', name: 'Ana de Armas', imageUrl: '/images/categories/actors/ana-de-armas.jpg', gender: 'female' },
    { id: 'ac-13', name: 'Timothée Chalamet', imageUrl: '/images/categories/actors/timothee-chalamet.jpg', gender: 'male' },
    { id: 'ac-14', name: 'Sydney Sweeney', imageUrl: '/images/categories/actors/sydney-sweeney.jpg', gender: 'female' },
    { id: 'ac-15', name: 'Keanu Reeves', imageUrl: '/images/categories/actors/keanu-reeves.jpg', gender: 'male' },
    { id: 'ac-16', name: 'Emma Stone', imageUrl: '/images/categories/actors/emma-stone.jpg', gender: 'female' },
    { id: 'ac-17', name: 'Will Smith', imageUrl: '/images/categories/actors/will-smith.jpg', gender: 'male' },
    { id: 'ac-18', name: 'Millie Bobby Brown', imageUrl: '/images/categories/actors/millie-bobby-brown.jpg', gender: 'female' },
    { id: 'ac-19', name: 'Pedro Pascal', imageUrl: '/images/categories/actors/pedro-pascal.jpg', gender: 'male' },
    { id: 'ac-20', name: 'Anya Taylor-Joy', imageUrl: '/images/categories/actors/anya-taylor-joy.jpg', gender: 'female' },
    { id: 'ac-21', name: 'Morgan Freeman', imageUrl: '/images/categories/actors/morgan-freeman.jpg', gender: 'male' },
    { id: 'ac-22', name: 'Viola Davis', imageUrl: '/images/categories/actors/viola-davis.jpg', gender: 'female' },
    { id: 'ac-23', name: 'Chris Pratt', imageUrl: '/images/categories/actors/chris-pratt.jpg', gender: 'male' },
    { id: 'ac-24', name: 'Jenna Ortega', imageUrl: '/images/categories/actors/jenna-ortega.jpg', gender: 'female' },
    { id: 'ac-25', name: 'Cillian Murphy', imageUrl: '/images/categories/actors/cillian-murphy.jpg', gender: 'male' },
    { id: 'ac-26', name: 'Sandra Bullock', imageUrl: '/images/categories/actors/sandra-bullock.jpg', gender: 'female' },
    { id: 'ac-27', name: 'Jason Momoa', imageUrl: '/images/categories/actors/jason-momoa.jpg', gender: 'male' },
    { id: 'ac-28', name: 'Lupita Nyong\'o', imageUrl: '/images/categories/actors/lupita-nyongo.jpg', gender: 'female' },
    { id: 'ac-29', name: 'Brad Pitt', imageUrl: '/images/categories/actors/brad-pitt.jpg', gender: 'male' },
    { id: 'ac-30', name: 'Angelina Jolie', imageUrl: '/images/categories/actors/angelina-jolie.jpg', gender: 'female' },
    { id: 'ac-31', name: 'Johnny Depp', imageUrl: '/images/categories/actors/johnny-depp.jpg', gender: 'male' },
    { id: 'ac-32', name: 'Tom Cruise', imageUrl: '/images/categories/actors/tom-cruise.jpg', gender: 'male' },
    { id: 'ac-33', name: 'Denzel Washington', imageUrl: '/images/categories/actors/denzel-washington.jpg', gender: 'male' },
    { id: 'ac-34', name: 'Halle Berry', imageUrl: '/images/categories/actors/halle-berry.jpg', gender: 'female' },
    { id: 'ac-35', name: 'Natalie Portman', imageUrl: '/images/categories/actors/natalie-portman.jpg', gender: 'female' },
    { id: 'ac-36', name: 'Christian Bale', imageUrl: '/images/categories/actors/christian-bale.jpg', gender: 'male' },
    { id: 'ac-37', name: 'Henry Cavill', imageUrl: '/images/categories/actors/henry-cavill.jpg', gender: 'male' },
    { id: 'ac-38', name: 'Gal Gadot', imageUrl: '/images/categories/actors/gal-gadot.jpg', gender: 'female' },
    { id: 'ac-39', name: 'Paul Rudd', imageUrl: '/images/categories/actors/paul-rudd.jpg', gender: 'male' },
    { id: 'ac-40', name: 'Benedict Cumberbatch', imageUrl: '/images/categories/actors/benedict-cumberbatch.jpg', gender: 'male' },
    { id: 'ac-41', name: 'Andrew Garfield', imageUrl: '/images/categories/actors/andrew-garfield.jpg', gender: 'male' },
    { id: 'ac-42', name: 'Daniel Kaluuya', imageUrl: '/images/categories/actors/daniel-kaluuya.jpg', gender: 'male' },
    { id: 'ac-43', name: 'Michael B. Jordan', imageUrl: '/images/categories/actors/michael-b-jordan.jpg', gender: 'male' },
    { id: 'ac-44', name: 'Idris Elba', imageUrl: '/images/categories/actors/idris-elba.jpg', gender: 'male' },
    { id: 'ac-45', name: 'Regé-Jean Page', imageUrl: '/images/categories/actors/rege-jean-page.jpg', gender: 'male' },
    { id: 'ac-46', name: 'Simu Liu', imageUrl: '/images/categories/actors/simu-liu.jpg', gender: 'male' },
    { id: 'ac-47', name: 'Awkwafina', imageUrl: '/images/categories/actors/awkwafina.jpg', gender: 'female' },
    { id: 'ac-48', name: 'Rachel Zegler', imageUrl: '/images/categories/actors/rachel-zegler.jpg', gender: 'female' },
    { id: 'ac-49', name: 'Hailee Steinfeld', imageUrl: '/images/categories/actors/hailee-steinfeld.jpg', gender: 'female' },
    { id: 'ac-50', name: 'Daisy Ridley', imageUrl: '/images/categories/actors/daisy-ridley.jpg', gender: 'female' },
  ],
};

const athletes: CategoryRoster = {
  id: 'athletes',
  label: 'Athletes',
  characters: [
    { id: 'at-01', name: 'LeBron James', imageUrl: '/images/categories/athletes/lebron-james.jpg', gender: 'male' },
    { id: 'at-02', name: 'Serena Williams', imageUrl: '/images/categories/athletes/serena-williams.jpg', gender: 'female' },
    { id: 'at-03', name: 'Lionel Messi', imageUrl: '/images/categories/athletes/lionel-messi.jpg', gender: 'male' },
    { id: 'at-04', name: 'Simone Biles', imageUrl: '/images/categories/athletes/simone-biles.jpg', gender: 'female' },
    { id: 'at-05', name: 'Cristiano Ronaldo', imageUrl: '/images/categories/athletes/cristiano-ronaldo.jpg', gender: 'male' },
    { id: 'at-06', name: 'Naomi Osaka', imageUrl: '/images/categories/athletes/naomi-osaka.jpg', gender: 'female' },
    { id: 'at-07', name: 'Stephen Curry', imageUrl: '/images/categories/athletes/stephen-curry.jpg', gender: 'male' },
    { id: 'at-08', name: 'Sha\'Carri Richardson', imageUrl: '/images/categories/athletes/shacarri-richardson.jpg', gender: 'female' },
    { id: 'at-09', name: 'Tom Brady', imageUrl: '/images/categories/athletes/tom-brady.jpg', gender: 'male' },
    { id: 'at-10', name: 'Alex Morgan', imageUrl: '/images/categories/athletes/alex-morgan.jpg', gender: 'female' },
    { id: 'at-11', name: 'Usain Bolt', imageUrl: '/images/categories/athletes/usain-bolt.jpg', gender: 'male' },
    { id: 'at-12', name: 'Megan Rapinoe', imageUrl: '/images/categories/athletes/megan-rapinoe.jpg', gender: 'female' },
    { id: 'at-13', name: 'Patrick Mahomes', imageUrl: '/images/categories/athletes/patrick-mahomes.jpg', gender: 'male' },
    { id: 'at-14', name: 'Katie Ledecky', imageUrl: '/images/categories/athletes/katie-ledecky.jpg', gender: 'female' },
    { id: 'at-15', name: 'Kevin Durant', imageUrl: '/images/categories/athletes/kevin-durant.jpg', gender: 'male' },
    { id: 'at-16', name: 'Coco Gauff', imageUrl: '/images/categories/athletes/coco-gauff.jpg', gender: 'female' },
    { id: 'at-17', name: 'Neymar', imageUrl: '/images/categories/athletes/neymar.jpg', gender: 'male' },
    { id: 'at-18', name: 'Eileen Gu', imageUrl: '/images/categories/athletes/eileen-gu.jpg', gender: 'female' },
    { id: 'at-19', name: 'Giannis Antetokounmpo', imageUrl: '/images/categories/athletes/giannis-antetokounmpo.jpg', gender: 'male' },
    { id: 'at-20', name: 'Sydney McLaughlin', imageUrl: '/images/categories/athletes/sydney-mclaughlin.jpg', gender: 'female' },
    { id: 'at-21', name: 'Kylian Mbappé', imageUrl: '/images/categories/athletes/kylian-mbappe.jpg', gender: 'male' },
    { id: 'at-22', name: 'Ronda Rousey', imageUrl: '/images/categories/athletes/ronda-rousey.jpg', gender: 'female' },
    { id: 'at-23', name: 'Mike Tyson', imageUrl: '/images/categories/athletes/mike-tyson.jpg', gender: 'male' },
    { id: 'at-24', name: 'Caitlin Clark', imageUrl: '/images/categories/athletes/caitlin-clark.jpg', gender: 'female' },
    { id: 'at-25', name: 'Shaquille O\'Neal', imageUrl: '/images/categories/athletes/shaquille-oneal.jpg', gender: 'male' },
    { id: 'at-26', name: 'Venus Williams', imageUrl: '/images/categories/athletes/venus-williams.jpg', gender: 'female' },
    { id: 'at-27', name: 'Tiger Woods', imageUrl: '/images/categories/athletes/tiger-woods.jpg', gender: 'male' },
    { id: 'at-28', name: 'Lindsey Vonn', imageUrl: '/images/categories/athletes/lindsey-vonn.jpg', gender: 'female' },
    { id: 'at-29', name: 'Roger Federer', imageUrl: '/images/categories/athletes/roger-federer.jpg', gender: 'male' },
    { id: 'at-30', name: 'Rafael Nadal', imageUrl: '/images/categories/athletes/rafael-nadal.jpg', gender: 'male' },
    { id: 'at-31', name: 'Novak Djokovic', imageUrl: '/images/categories/athletes/novak-djokovic.jpg', gender: 'male' },
    { id: 'at-32', name: 'Lewis Hamilton', imageUrl: '/images/categories/athletes/lewis-hamilton.jpg', gender: 'male' },
    { id: 'at-33', name: 'Max Verstappen', imageUrl: '/images/categories/athletes/max-verstappen.jpg', gender: 'male' },
    { id: 'at-34', name: 'Michael Jordan', imageUrl: '/images/categories/athletes/michael-jordan.jpg', gender: 'male' },
    { id: 'at-35', name: 'Kobe Bryant', imageUrl: '/images/categories/athletes/kobe-bryant.jpg', gender: 'male' },
    { id: 'at-36', name: 'David Beckham', imageUrl: '/images/categories/athletes/david-beckham.jpg', gender: 'male' },
    { id: 'at-37', name: 'Zlatan Ibrahimović', imageUrl: '/images/categories/athletes/zlatan-ibrahimovic.jpg', gender: 'male' },
    { id: 'at-38', name: 'Erling Haaland', imageUrl: '/images/categories/athletes/erling-haaland.jpg', gender: 'male' },
    { id: 'at-39', name: 'Virat Kohli', imageUrl: '/images/categories/athletes/virat-kohli.jpg', gender: 'male' },
    { id: 'at-40', name: 'Sachin Tendulkar', imageUrl: '/images/categories/athletes/sachin-tendulkar.jpg', gender: 'male' },
    { id: 'at-41', name: 'Tyson Fury', imageUrl: '/images/categories/athletes/tyson-fury.jpg', gender: 'male' },
    { id: 'at-42', name: 'Anthony Joshua', imageUrl: '/images/categories/athletes/anthony-joshua.jpg', gender: 'male' },
    { id: 'at-43', name: 'Conor McGregor', imageUrl: '/images/categories/athletes/conor-mcgregor.jpg', gender: 'male' },
    { id: 'at-44', name: 'Floyd Mayweather Jr.', imageUrl: '/images/categories/athletes/floyd-mayweather-jr.jpg', gender: 'male' },
    { id: 'at-45', name: 'Manny Pacquiao', imageUrl: '/images/categories/athletes/manny-pacquiao.jpg', gender: 'male' },
    { id: 'at-46', name: 'Mikaela Shiffrin', imageUrl: '/images/categories/athletes/mikaela-shiffrin.jpg', gender: 'female' },
    { id: 'at-47', name: 'Allyson Felix', imageUrl: '/images/categories/athletes/allyson-felix.jpg', gender: 'female' },
    { id: 'at-48', name: 'Mo Farah', imageUrl: '/images/categories/athletes/mo-farah.jpg', gender: 'male' },
    { id: 'at-49', name: 'Oscar Pistorius', imageUrl: '/images/categories/athletes/oscar-pistorius.jpg', gender: 'male' },
    { id: 'at-50', name: 'Didier Drogba', imageUrl: '/images/categories/athletes/didier-drogba.jpg', gender: 'male' },
  ],
};

const bibleCharacters: CategoryRoster = {
  id: 'bible_characters',
  label: 'Bible Characters',
  characters: [
    { id: 'bi-01', name: 'Moses', imageUrl: '/images/categories/bible-characters/moses.jpg', gender: 'male' },
    { id: 'bi-02', name: 'Mary', imageUrl: '/images/categories/bible-characters/mary.jpg', gender: 'female' },
    { id: 'bi-03', name: 'David', imageUrl: '/images/categories/bible-characters/david.jpg', gender: 'male' },
    { id: 'bi-04', name: 'Esther', imageUrl: '/images/categories/bible-characters/esther.jpg', gender: 'female' },
    { id: 'bi-05', name: 'Abraham', imageUrl: '/images/categories/bible-characters/abraham.jpg', gender: 'male' },
    { id: 'bi-06', name: 'Ruth', imageUrl: '/images/categories/bible-characters/ruth.jpg', gender: 'female' },
    { id: 'bi-07', name: 'Noah', imageUrl: '/images/categories/bible-characters/noah.jpg', gender: 'male' },
    { id: 'bi-08', name: 'Deborah', imageUrl: '/images/categories/bible-characters/deborah.jpg', gender: 'female' },
    { id: 'bi-09', name: 'Joseph', imageUrl: '/images/categories/bible-characters/joseph.jpg', gender: 'male' },
    { id: 'bi-10', name: 'Rahab', imageUrl: '/images/categories/bible-characters/rahab.jpg', gender: 'female' },
    { id: 'bi-11', name: 'Daniel', imageUrl: '/images/categories/bible-characters/daniel.jpg', gender: 'male' },
    { id: 'bi-12', name: 'Sarah', imageUrl: '/images/categories/bible-characters/sarah.jpg', gender: 'female' },
    { id: 'bi-13', name: 'Samson', imageUrl: '/images/categories/bible-characters/samson.jpg', gender: 'male' },
    { id: 'bi-14', name: 'Hannah', imageUrl: '/images/categories/bible-characters/hannah.jpg', gender: 'female' },
    { id: 'bi-15', name: 'Elijah', imageUrl: '/images/categories/bible-characters/elijah.jpg', gender: 'male' },
    { id: 'bi-16', name: 'Miriam', imageUrl: '/images/categories/bible-characters/miriam.jpg', gender: 'female' },
    { id: 'bi-17', name: 'Solomon', imageUrl: '/images/categories/bible-characters/solomon.jpg', gender: 'male' },
    { id: 'bi-18', name: 'Rebekah', imageUrl: '/images/categories/bible-characters/rebekah.jpg', gender: 'female' },
    { id: 'bi-19', name: 'Peter', imageUrl: '/images/categories/bible-characters/peter.jpg', gender: 'male' },
    { id: 'bi-20', name: 'Mary Magdalene', imageUrl: '/images/categories/bible-characters/mary-magdalene.jpg', gender: 'female' },
    { id: 'bi-21', name: 'Paul', imageUrl: '/images/categories/bible-characters/paul.jpg', gender: 'male' },
    { id: 'bi-22', name: 'Eve', imageUrl: '/images/categories/bible-characters/eve.jpg', gender: 'female' },
    { id: 'bi-23', name: 'Adam', imageUrl: '/images/categories/bible-characters/adam.jpg', gender: 'male' },
    { id: 'bi-24', name: 'Delilah', imageUrl: '/images/categories/bible-characters/delilah.jpg', gender: 'female' },
    { id: 'bi-25', name: 'Joshua', imageUrl: '/images/categories/bible-characters/joshua.jpg', gender: 'male' },
    { id: 'bi-26', name: 'Jezebel', imageUrl: '/images/categories/bible-characters/jezebel.jpg', gender: 'female' },
    { id: 'bi-27', name: 'Jonah', imageUrl: '/images/categories/bible-characters/jonah.jpg', gender: 'male' },
    { id: 'bi-28', name: 'Bathsheba', imageUrl: '/images/categories/bible-characters/bathsheba.jpg', gender: 'female' },
    { id: 'bi-29', name: 'Jesus Christ', imageUrl: '/images/categories/bible-characters/jesus-christ.jpg', gender: 'male' },
    { id: 'bi-30', name: 'Isaac', imageUrl: '/images/categories/bible-characters/isaac.jpg', gender: 'male' },
    { id: 'bi-31', name: 'Jacob', imageUrl: '/images/categories/bible-characters/jacob.jpg', gender: 'male' },
    { id: 'bi-32', name: 'Esau', imageUrl: '/images/categories/bible-characters/esau.jpg', gender: 'male' },
    { id: 'bi-33', name: 'Aaron', imageUrl: '/images/categories/bible-characters/aaron.jpg', gender: 'male' },
    { id: 'bi-34', name: 'Samuel', imageUrl: '/images/categories/bible-characters/samuel.jpg', gender: 'male' },
    { id: 'bi-35', name: 'Saul', imageUrl: '/images/categories/bible-characters/saul.jpg', gender: 'male' },
    { id: 'bi-36', name: 'Isaiah', imageUrl: '/images/categories/bible-characters/isaiah.jpg', gender: 'male' },
    { id: 'bi-37', name: 'Jeremiah', imageUrl: '/images/categories/bible-characters/jeremiah.jpg', gender: 'male' },
    { id: 'bi-38', name: 'Ezekiel', imageUrl: '/images/categories/bible-characters/ezekiel.jpg', gender: 'male' },
    { id: 'bi-39', name: 'Job', imageUrl: '/images/categories/bible-characters/job.jpg', gender: 'male' },
    { id: 'bi-40', name: 'Boaz', imageUrl: '/images/categories/bible-characters/boaz.jpg', gender: 'male' },
    { id: 'bi-41', name: 'Lot', imageUrl: '/images/categories/bible-characters/lot.jpg', gender: 'male' },
    { id: 'bi-42', name: 'Gideon', imageUrl: '/images/categories/bible-characters/gideon.jpg', gender: 'male' },
    { id: 'bi-43', name: 'Barak', imageUrl: '/images/categories/bible-characters/barak.jpg', gender: 'male' },
    { id: 'bi-44', name: 'Tamar', imageUrl: '/images/categories/bible-characters/tamar.jpg', gender: 'female' },
    { id: 'bi-45', name: 'Zipporah', imageUrl: '/images/categories/bible-characters/zipporah.jpg', gender: 'female' },
    { id: 'bi-46', name: 'Elizabeth', imageUrl: '/images/categories/bible-characters/elizabeth.jpg', gender: 'female' },
    { id: 'bi-47', name: 'John the Baptist', imageUrl: '/images/categories/bible-characters/john-the-baptist.jpg', gender: 'male' },
    { id: 'bi-48', name: 'Thomas', imageUrl: '/images/categories/bible-characters/thomas.jpg', gender: 'male' },
    { id: 'bi-49', name: 'Judas Iscariot', imageUrl: '/images/categories/bible-characters/judas-iscariot.jpg', gender: 'male' },
    { id: 'bi-50', name: 'Barnabas', imageUrl: '/images/categories/bible-characters/barnabas.jpg', gender: 'male' },
  ],
};

const famousFaces: CategoryRoster = {
  id: 'famous_faces',
  label: 'Famous Faces',
  characters: [
    { id: 'ff-01', name: 'Elon Musk', imageUrl: '/images/categories/famous-faces/elon-musk.jpg', gender: 'male' },
    { id: 'ff-02', name: 'Oprah Winfrey', imageUrl: '/images/categories/famous-faces/oprah-winfrey.jpg', gender: 'female' },
    { id: 'ff-03', name: 'Barack Obama', imageUrl: '/images/categories/famous-faces/barack-obama.jpg', gender: 'male' },
    { id: 'ff-04', name: 'Michelle Obama', imageUrl: '/images/categories/famous-faces/michelle-obama.jpg', gender: 'female' },
    { id: 'ff-05', name: 'Mark Zuckerberg', imageUrl: '/images/categories/famous-faces/mark-zuckerberg.jpg', gender: 'male' },
    { id: 'ff-06', name: 'Malala Yousafzai', imageUrl: '/images/categories/famous-faces/malala-yousafzai.jpg', gender: 'female' },
    { id: 'ff-07', name: 'Jeff Bezos', imageUrl: '/images/categories/famous-faces/jeff-bezos.jpg', gender: 'male' },
    { id: 'ff-08', name: 'Kim Kardashian', imageUrl: '/images/categories/famous-faces/kim-kardashian.jpg', gender: 'female' },
    { id: 'ff-09', name: 'Bill Gates', imageUrl: '/images/categories/famous-faces/bill-gates.jpg', gender: 'male' },
    { id: 'ff-10', name: 'Taylor Lorenz', imageUrl: '/images/categories/famous-faces/taylor-lorenz.jpg', gender: 'female' },
    { id: 'ff-11', name: 'Donald Trump', imageUrl: '/images/categories/famous-faces/donald-trump.jpg', gender: 'male' },
    { id: 'ff-12', name: 'Greta Thunberg', imageUrl: '/images/categories/famous-faces/greta-thunberg.jpg', gender: 'female' },
    { id: 'ff-13', name: 'Joe Rogan', imageUrl: '/images/categories/famous-faces/joe-rogan.jpg', gender: 'male' },
    { id: 'ff-14', name: 'Alexandria Ocasio-Cortez', imageUrl: '/images/categories/famous-faces/alexandria-ocasio-cortez.jpg', gender: 'female' },
    { id: 'ff-15', name: 'Neil deGrasse Tyson', imageUrl: '/images/categories/famous-faces/neil-degrasse-tyson.jpg', gender: 'male' },
    { id: 'ff-16', name: 'Emma Watson', imageUrl: '/images/categories/famous-faces/emma-watson.jpg', gender: 'female' },
    { id: 'ff-17', name: 'Gordon Ramsay', imageUrl: '/images/categories/famous-faces/gordon-ramsay.jpg', gender: 'male' },
    { id: 'ff-18', name: 'Kylie Jenner', imageUrl: '/images/categories/famous-faces/kylie-jenner.jpg', gender: 'female' },
    { id: 'ff-19', name: 'Snoop Dogg', imageUrl: '/images/categories/famous-faces/snoop-dogg.jpg', gender: 'male' },
    { id: 'ff-20', name: 'Serena Williams', imageUrl: '/images/categories/famous-faces/serena-williams.jpg', gender: 'female' },
    { id: 'ff-21', name: 'Steve Harvey', imageUrl: '/images/categories/famous-faces/steve-harvey.jpg', gender: 'male' },
    { id: 'ff-22', name: 'Ellen DeGeneres', imageUrl: '/images/categories/famous-faces/ellen-degeneres.jpg', gender: 'female' },
    { id: 'ff-23', name: 'Kevin Hart', imageUrl: '/images/categories/famous-faces/kevin-hart.jpg', gender: 'male' },
    { id: 'ff-24', name: 'Martha Stewart', imageUrl: '/images/categories/famous-faces/martha-stewart.jpg', gender: 'female' },
    { id: 'ff-25', name: 'Dwayne Johnson', imageUrl: '/images/categories/famous-faces/dwayne-johnson.jpg', gender: 'male' },
    { id: 'ff-26', name: 'Queen Elizabeth II', imageUrl: '/images/categories/famous-faces/queen-elizabeth-ii.jpg', gender: 'female' },
    { id: 'ff-27', name: 'Pope Francis', imageUrl: '/images/categories/famous-faces/pope-francis.jpg', gender: 'male' },
    { id: 'ff-28', name: 'Ruth Bader Ginsburg', imageUrl: '/images/categories/famous-faces/ruth-bader-ginsburg.jpg', gender: 'female' },
    { id: 'ff-29', name: 'Beyoncé', imageUrl: '/images/categories/famous-faces/beyonce.jpg', gender: 'female' },
    { id: 'ff-30', name: 'Taylor Swift', imageUrl: '/images/categories/famous-faces/taylor-swift.jpg', gender: 'female' },
    { id: 'ff-31', name: 'Rihanna', imageUrl: '/images/categories/famous-faces/rihanna.jpg', gender: 'female' },
    { id: 'ff-32', name: 'Drake', imageUrl: '/images/categories/famous-faces/drake.jpg', gender: 'male' },
    { id: 'ff-33', name: 'Kanye West', imageUrl: '/images/categories/famous-faces/kanye-west.jpg', gender: 'male' },
    { id: 'ff-34', name: 'Jay-Z', imageUrl: '/images/categories/famous-faces/jay-z.jpg', gender: 'male' },
    { id: 'ff-35', name: 'Justin Bieber', imageUrl: '/images/categories/famous-faces/justin-bieber.jpg', gender: 'male' },
    { id: 'ff-36', name: 'Ariana Grande', imageUrl: '/images/categories/famous-faces/ariana-grande.jpg', gender: 'female' },
    { id: 'ff-37', name: 'Selena Gomez', imageUrl: '/images/categories/famous-faces/selena-gomez.jpg', gender: 'female' },
    { id: 'ff-38', name: 'Lady Gaga', imageUrl: '/images/categories/famous-faces/lady-gaga.jpg', gender: 'female' },
    { id: 'ff-39', name: 'Kim Jong Un', imageUrl: '/images/categories/famous-faces/kim-jong-un.jpg', gender: 'male' },
    { id: 'ff-40', name: 'Vladimir Putin', imageUrl: '/images/categories/famous-faces/vladimir-putin.jpg', gender: 'male' },
    { id: 'ff-41', name: 'Joe Biden', imageUrl: '/images/categories/famous-faces/joe-biden.jpg', gender: 'male' },
    { id: 'ff-42', name: 'Kamala Harris', imageUrl: '/images/categories/famous-faces/kamala-harris.jpg', gender: 'female' },
    { id: 'ff-43', name: 'Rishi Sunak', imageUrl: '/images/categories/famous-faces/rishi-sunak.jpg', gender: 'male' },
    { id: 'ff-44', name: 'Boris Johnson', imageUrl: '/images/categories/famous-faces/boris-johnson.jpg', gender: 'male' },
    { id: 'ff-45', name: 'MrBeast', imageUrl: '/images/categories/famous-faces/mrbeast.jpg', gender: 'male' },
    { id: 'ff-46', name: 'KSI', imageUrl: '/images/categories/famous-faces/ksi.jpg', gender: 'male' },
    { id: 'ff-47', name: 'Logan Paul', imageUrl: '/images/categories/famous-faces/logan-paul.jpg', gender: 'male' },
    { id: 'ff-48', name: 'Andrew Tate', imageUrl: '/images/categories/famous-faces/andrew-tate.jpg', gender: 'male' },
    { id: 'ff-49', name: 'Jordan Peterson', imageUrl: '/images/categories/famous-faces/jordan-peterson.jpg', gender: 'male' },
    { id: 'ff-50', name: 'David Attenborough', imageUrl: '/images/categories/famous-faces/david-attenborough.jpg', gender: 'male' },
  ],
};

export const categoryRosters: CategoryRoster[] = [
  digitalCreators,
  musicArtists,
  actors,
  athletes,
  bibleCharacters,
  famousFaces,
];

export function getCategoryRoster(category: Category): CategoryRoster | null {
  return categoryRosters.find(r => r.id === category) ?? null;
}
